# Generated by Django 3.2.6 on 2021-09-05 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0002_kb_type_lt_category_lt_status_t_rank_t_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='KB_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, max_length=575, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.kb_type')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=125)),
                ('file', models.FileField(max_length=500, upload_to='attachments')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('attached_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='knowledge_base.kb_entry')),
            ],
        ),
    ]
