from django.urls import path
from . import views
from .views import SettingsView


app_name = 'settings'

urlpatterns = [
    path('', SettingsView.as_view(), name='settings'),
    path('bstatus/', views.bugstatus_list, name='bug_status'),
    path('bstatus/add/', views.add_bugstatus, name='add_bstatus'),
    path('bstatus/<int:pk>/', views.bugstatus_detail, name='bstatus_detail'),
    path('bstatus/update/<int:pk>', views.update_bugstatus, name='bstatus_update'),
    path('bstatus/delete/<int:pk>', views.delete_bugstatus, name='bstatus_delete'),
    path('bpriority/', views.bugpriority_list, name='bug_priority'),
    path('bpriority/add/', views.add_bugpriority, name='add_bpriority'),
    path('bpriority/<int:pk>/', views.bugpriority_detail, name='bpriority_detail'),
    path('bpriority/update/<int:pk>/', views.update_bugpriority, name='bpriority_update'),
    path('bpriority/delete/<int:pk>/', views.delete_td_priority, name='bpriority_delete'),
    path('bcategory/', views.bugcategory_list, name='bug_category'),
    path('bcategory/add/', views.add_bugcategory, name='add_bcategory'),
    path('bcategory/<int:pk>/', views.category_bugdetail, name='bcategory_detail'),
    path('bcategory/update/<int:pk>/', views.update_bugcategory, name='bcategory_update'),
    path('bcategory/delete/<int:pk>/', views.delete_bugcategory, name='bcategory_delete'),
    path('tdstatus/', views.td_status_list, name='td_status'),
    path('tdstatus/add/', views.add_td_status, name='add_tdstatus'),
    path('tdstatus/<int:pk>/', views.td_status_detail, name='tdstatus_detail'),
    path('tdstatus/update/<int:pk>/', views.update_td_status, name='tdstatus_update'),
    path('tdstatus/delete/<int:pk>/', views.delete_td_status, name='tdstatus_delete'),
    path('tdpriority/', views.td_priority_list, name='td_priority'),
    path('tdpriority/add/', views.add_td_priority, name='add_td_priority'),
    path('tdpriority/<int:pk>/', views.td_priority_detail, name='td_priority_detail'),
    path('tdpriority/update/<int:pk>/', views.update_td_priority, name='td_priority_update'),
    path('tdpriority/delete/<int:pk>/', views.delete_td_priority, name='td_priority_delete'),
    path('ltstatus/', views.lt_status_list, name='lt_status'),
    path('ltstatus/add/', views.add_lt_status, name='add_ltstatus'),
    path('ltstatus/<int:pk>/', views.lt_status_detail, name='ltstatus_detail'),
    path('ltstatus/update/<int:pk>/', views.update_lt_status, name='ltstatus_update'),
    path('ltstatus/delete/<int:pk>/', views.delete_lt_status, name='ltstatus_delete'),
    path('ltcategory/', views.lt_category_list, name='lt_category'),
    path('ltcategory/add/', views.add_lt_category, name='add_ltcategory'),
    path('ltcategory/<int:pk>/', views.lt_category_detail, name='ltcategory_detail'),
    path('ltcategory/update/<int:pk>/', views.update_lt_category, name='ltcategory_update'),
    path('ltcategory/delete/<int:pk>/', views.delete_lt_category, name='ltcategory_delete'),
    path('tstatus/', views.t_status_list, name='t_status'),
    path('tstatus/add/', views.add_tstatus, name='add_tstatus'),
    path('tstatus/<int:pk>/', views.t_status_detail, name='t_status_detail'),
    path('tstatus/update/<int:pk>/', views.update_tstatus, name='update_tstatus'),
    path('tstatus/delete/<int:pk>/', views.delete_tstatus, name='delete_tstatus'),
    path('trank/', views.t_rank_list, name='t_rank'),
    path('trank/add/', views.add_trank, name='add_trank'),
    path('trank/<int:pk>/', views.t_rank_detail, name='t_rank_detail'),
    path('trank/update/<int:pk>/', views.update_trank, name='update_trank'),
    path('trank/delete/<int:pk>/', views.delete_trank, name='delete_trank'),
    path('kbtype/', views.kb_type_list, name='kb_type'),
    path('kbtype/add/', views.add_kbtype, name='add_kbtype'),
    path('kbtype/<int:pk>/', views.kb_type_list, name='kb_type_detail'),
    path('kbtype/update/<int:pk>/', views.update_kbtype, name='update_kbtype'),
    path('kbtype/delete/<int:pk>/', views.delete_kbtype, name='delete_kbtype')
]
