# Generated by Django 3.2.6 on 2021-08-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.td_priority'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.td_status'),
        ),
        migrations.DeleteModel(
            name='TD_Priority',
        ),
        migrations.DeleteModel(
            name='TDStatus',
        ),
    ]
