# Generated by Django 3.2.6 on 2021-09-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0002_kb_type_lt_category_lt_status_t_rank_t_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.lt_category')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.lt_status')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=275, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('linked_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkedTasks.linkedtasks')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.t_rank')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.t_status')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, max_length=550, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noted_on', to='linkedTasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=125)),
                ('file', models.FileField(max_length=500, upload_to='attachments')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('attached_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='linkedTasks.linkedtasks')),
            ],
        ),
    ]
