# Generated by Django 3.2.6 on 2021-09-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_kb_type_lt_category_lt_status_t_rank_t_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug_status',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lt_status',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_status',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='td_status',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
