# Generated by Django 3.2.6 on 2021-08-28 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('Bug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.bug_category'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.bug_priority'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.bug_status'),
        ),
        migrations.DeleteModel(
            name='BugCategory',
        ),
        migrations.DeleteModel(
            name='BugPriority',
        ),
        migrations.DeleteModel(
            name='BugStatus',
        ),
    ]
